version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - echo Building the Go code...
      - go build
      - curl 'https://www.google.com'
      - echo you did it

