---
version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go build -v ./... && go test -v ./...

workflows:
  version: 2
  doit:
    jobs:
      - test