---
version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck
      - run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.6.1
      - run: go build -v ./... && go test -v ./...
      - run: staticcheck *.go
      - run: gosec .

workflows:
  version: 2
  doit:
    jobs:
      - test