name: Build and test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.4"
      - name: Build
        run: go build -v ./... && go test -v ./...
      - name: Gosec
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.6.1 && gosec .
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
