name: Build and test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.4"
      - name: Build
        run: go build -v ./... && go test -v ./...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
